export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    image: '/images/1.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://github.com/asigitj',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://github.com/asigitj',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '/images/3.jpg',
    tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://github.com/asigitj',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://github.com/asigitj',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey', },
  { year: 2016, text: 'Study at Bina Sarana Informatika University', },
  { year: 2017, text: 'Worked as staff Operational for PT. Sukma Nusantara transport', },
  { year: 2020, text: 'Graduate from College', },
  { year: 2021, text: 'Worked as Online Shop Admin for STAR17 Computer', },
  { year: 2021, text: 'Interested in Software Development and other Technologies, also liked to learn both of them', },
  { year: 2022, text: 'After a few months of learning, it was obvious that I was ready to look for my first job', },
  // { year: 2000, text: 'Worked as a freelance developer', },
  // { year: 2000, text: 'Founded JavaScript Mastery', },
  // { year: 2000, text: 'Shared my projects with the world', },
  // { year: 2000, text: 'Started my own platform', },
];